### PR TITLE
adding multistate tutorial

### PR DESCRIPTION
**Pull request by wrightaprilm**
Hi all, added a tutorial describing how to partition multistate characters with the Mk model. We might consider making this the default morphology tutorial.

### CODE REVIEW

**Review by azwaans — CHANGES_REQUESTED** [review]
Hello ! While going through the tutorial we weren’t able to make the last part compile. It seemed like the code provided to create the Q matrix works with binary characters only, which results in an error in the CTMC. We couldn't find an obvious way to adapt it. We also noticed the bears.nex datafile and corresponding scripts are provided in addition to the cinctans.nex. Were they left for reference ?

**Comment by wrightaprilm** [comment]
I forgot to add an `exclude` block to the header to remove the bears scripts and data. That's fixed now.

With respect to the error: I added a line to the tutorial to exclude non-binary characters for the choose-your-own-adventure. Mostly due to tractability of completing the model in the classroom setting. I also added an example of incorporating the Dirichlet model into a matrix partitioning loop to allow each character state space to have its own state frequency variation. Let me know what you think of that.

**Review by azwaans — APPROVED** [review]
Thank you for the changes, it's all clear from our side now!

**Review by Jeremy-Andreoletti — APPROVED** [review]
I consider this great tutorial ready for merging too!

**Comment by wrightaprilm** [comment]
Thanks, y'all. I've been using some variant of it since the [RevBayes Workshop](https://dwbapst.github.io/PaleoSoc_phylo_short_course_2019/) at the US Geological Society meetings.

It looks like we've met the new guidelines for review outlined in #10. Is that right, @bjoelle? If so, I'll go ahead and merge this.

**Pull request merged**
