### PR TITLE
Updating Xcode internal build instructions

### PR DESCRIPTION
**Pull request by davidcerny**
Updating the [tutorial on setting up Xcode](https://revbayes.github.io/developer/setup/#xcode) for RevBayes development to make it applicable to newer versions of macOS (version used in this PR: Monterey), Xcode (version used in this PR: 14.2), and RevBayes itself. In particular, after PR [#278](https://github.com/revbayes/revbayes/pull/278), we now need to compile under the C++17 dialect. Some of the screenshots used in the tutorial were less than informative or accidentally duplicated, so I replaced those too.

### CODE REVIEW

**Comment by davidcerny** [comment]
Thanks for merging this, Ben! That said, I'm wondering if the Xcode instructions should be updated once again, given what @mlandis recently reported on Slack (after I opened this PR)...

**Comment by bredelings** [comment]
Good point!  I talked with @mlandis, and I think that the real solution was to use the most recent version of boost (version 1.83).  Mike had to compile boost 1.83 himself because homebrew was stuck on 1.82 for a while, but it looks like homebrew finally got version 1.83.  So (fingers crossed) hopefully users of XCode 14 shouldn't have to do anything?

**Comment by davidcerny** [comment]
Ah, that's great to hear! So the `_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION` preprocessor macro is not necessary when using boost 1.83?

**Comment by bredelings** [comment]
Yeah, if using boost 1.83, its not necessary.

**Pull request merged**
